openapi: 3.0.1
info:
  title: Sistema CCS - Secutiry User Data
  version: 1.0.0
  description: >-
    Permite consultar la información asociada a los usuarios del sistema y validar su identidad
servers:
  - url: >-
      https://sistema-ccs/v1/reference-data/validate-information
paths:
  /credentials/validate-information:
    post:
      operationId: validate
      x-api-type: proxy-jwt
      summary: >-
        Realiza la validación de las credenciales del usuario.
      description: >
        ### Clasificación de la información: Privado

        Realiza la validación de las credenciales del usuario en el sistema CCS
        
      parameters:
        - $ref: "#/components/parameters/json-web-token"
        - $ref: "#/components/parameters/x-client-certificate"
        - $ref: "#/components/parameters/authorization"
        - $ref: "#/components/parameters/accept"
        - $ref: "#/components/parameters/message-id"

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/validateRequest'
            examples:
              Autenticación del usuario válida:
                description: 
                  <b>Dado:</b> Dado que se desea ingresar al módulo administrativo del sistema CCS, el usuario ingresa su alias y contraseñas asignadas.<p>
                  <b>Cuando:</b> se envían los datos, se valida que efectivamente el alias y la contraseña sean correctos y se correspondan entre si <p>
                  <b>Entonces:</b> se envía la clave dinámica al correo registrado por el usuario como correo principal<p>
                value:
                  data:
                    usersCredentials:
                      aliasName: jhrodriguez
                      credentials: 9EKH/OMzOx2L6ZG3iLIRFQRN

              Autenticación del usuario no válida:
                description: 
                  <b>Dado:</b> Dado que se desea ingresar al módulo administrativo del sistema CCS, el usuario ingresa su alias y contraseñas asignadas.<p>
                  <b>Cuando:</b> se envían los datos, se comprueba que el alias y/o la contraseña no son correctos<p>
                  <b>Entonces:</b> se genera un error informando que falló la autenticación<p> 
                value:
                  data:
                    usersCredentials:
                      aliasName: jhrodriguez
                      credentials: 9EKH/OMzOx2L6ZG3iLIRFQRN

              Faltan_parámetros_obligatorios:
                description: 
                  <b>Dado:</b> Que no se envian todos los datos obligatorios.<p>
                  <b>Cuando:</b> se consume el api<p>
                  <b>Entonces:</b> Se recibe un mensaje de excepción<p>      
                value:
                  data:
                    userCredentials:
                      aliasName: jhrodriguez
                      credentials: 
        required: true
      responses:
        '200':
          x-success-response: Successfull
          description: Respuesta exitosa
          x-ibm-languages:
            description:
              en: Successful response.          
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validateResponse'
              examples:
                Autenticación del usuario válida:
                  description: 
                    <b>Dado:</b> Dado que se desea ingresar al módulo administrativo del sistema CCS, el usuario ingresa su alias y contraseñas asignadas.<p>
                    <b>Cuando:</b> se envían los datos, se valida que efectivamente el alias y la contraseña sean correctos y se correspondan entre si <p>
                    <b>Entonces:</b> se envía la clave dinámica al correo registrado por el usuario como correo principal<p>
                  value:
                    data:
                      meta:
                        _requestDateTime: '2024-01-26T14:52:09.779Z'
                        _applicationId: default
                        _messageId: dbff089d-292d-4894-b842-8e88c7003525
                      message: >-
                        La información se ha enviado a su correo
                        electrónico
                      expireDate: '2024-01-26T15:05:09.779Z'

        '400':
          description: Bad request
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              examples:
                Faltan parámetros obligatorios:
                      description: 
                        <b>Dado:</b> Que no se envian todos los datos obligatorios.<p>
                        <b>Cuando:</b> se consume el api<p>
                        <b>Entonces:</b> Se recibe un mensaje de excepción<p> 
                      value:
                        data:
                         meta:
                          _requestDateTime: '2024-01-26T14:52:09.779Z'
                          _applicationId: default
                          _messageId: dbff089d-292d-4894-b842-8e88c7003525
                         status: 400
                         title: Bad Resquest
                         errors:
                          - code: BP20252
                            detail: Faltan parámetros obligatorios (credentials)
          x-ibm-languages:
            description:
              en: Error in the request.
        '401':
          description: Credenciales incorrectas.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              examples:
                Autenticación del usuario no válida:
                  description: 
                    <b>Dado:</b> Dado que se desea ingresar al módulo administrativo del sistema CCS, el usuario ingresa su alias y contraseñas asignadas.<p>
                    <b>Cuando:</b> se envían los datos, se comprueba que el alias y/o la contraseña no son correctos<p>
                    <b>Entonces:</b> se genera un error informando que falló la autenticación<p>
                  value:
                    data:
                     meta:
                      _requestDateTime: '2024-01-26T14:52:09.779Z'
                      _applicationId: default
                      _messageId: dbff089d-292d-4894-b842-8e88c7003525
                     status: 401
                     title: Unauthorized (RFC 7235)
                     errors:
                      - code: BP20256
                        detail: Evento no autorizado
          x-ibm-languages:
            description:
              en: Incorrect credentials.
        '404':
          description: Recurso no encontrado.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              examples:
                Usuario no se encuentra registrado:
                  description: 
                    <b>Dado:</b> Que se envía un alias de un usuario no registrado.<p>
                    <b>Cuando:</b> se consume el api<p>
                    <b>Entonces:</b> Se recibe un mensaje de excepción<p>       
                  value:
                    data:
                     meta:
                      _requestDateTime: '2024-01-26T14:52:09.779Z'
                      _applicationId: default
                      _messageId: dbff089d-292d-4894-b842-8e88c7003525
                     status: 404
                     title: Not Found
                     errors:
                      - code: BP20250
                        detail: No se encontraron registros

          x-ibm-languages:
            description:
              en: Resource not found.
        '409':
          description: >
            El estado del recurso presenta conflictos con los datos de la solicitud.
            ### Códigos de error
            Listado de códigos de error
            | code    | detail                        |
            | ------- | ----------------------------- |
            | BP20269 | Se requiere autenticación     | 

          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              examples:
                Identificador de relación cliente-comercio vencido:
                  description: 
                    <b>Dado:</b> Que se recibe un usuario con credenciales vencidas.<p>
                    <b>Cuando:</b> se consume el api<p>
                    <b>Entonces:</b> Se recibe un mensaje de excepción<p>    
                  value:
                    data:
                     meta:
                      _requestDateTime: '2024-01-26T14:52:09.779Z'
                      _applicationId: default
                      _messageId: dbff089d-292d-4894-b842-8e88c7003525
                     status: 409
                     title: Conflict
                     errors:
                      - code: BP20269
                        detail: Usuario con autenticación vencida
                
          x-ibm-languages:
            description:
              en: Resource state has conflicts with data of the request.
        '500':
          description: Error interno del servidor.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 500
                title: Internal Server Error
                errors:
                  - code: BP20257
                    detail: El evento no pudo ser realizado, intente nuevamente.
          x-ibm-languages:
            description:
              en: Internal server error.
        '502':
          description: Error en la respuesta del proveedor del servicio.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 502
                title: Bad Gateway
                errors:
                  - code: BP20257
                    detail: El evento no pudo ser realizado, intente nuevamente.
          x-ibm-languages:
            description:
              en: Error in the service provider response.
        '503':
          description: Servicio no disponible.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 503
                title: Service Unavailable
                errors:
                  - code: BP20257
                    detail: El evento no pudo ser realizado, intente nuevamente.
          x-ibm-languages:
            description:
              en: Service unavailable.
        '504':
          description: Tiempo de respuesta del proveedor del servicio excedido.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 504
                title: Gateway Timeout
                errors:
                  - code: BP20257
                    detail: El evento no pudo ser realizado, intente nuevamente.
          x-ibm-languages:
            description:
              en: Service provider response time exceeded.
      x-codegen-request-body-name: requestBody
      tags:
        - Validate user credentials
      security:
        - clientSecret: []
          clientId: []
          
  /credentials/dynamicKey:
    post:
      operationId: validateDynamicKey
      x-api-type: proxy-jwt
      summary: >-
        Realiza la validación de la clave dinámica.
      description: >
        ### Clasificación de la información: Privado

        Realiza la validación de la clave temporal enviada al correo del usuario
        
      parameters:
        - $ref: "#/components/parameters/json-web-token"
        - $ref: "#/components/parameters/x-client-certificate"
        - $ref: "#/components/parameters/authorization"
        - $ref: "#/components/parameters/accept"
        - $ref: "#/components/parameters/message-id"

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dynamicKeyRequest'
            examples:
              Clave dinámica válida:
                description: 
                  <b>Dado:</b> Dado que se desea ingresar al módulo administrativo del sistema CCS, el usuario ingresa la clave dinámica recibida por correo.<p>
                  <b>Cuando:</b> se envían los datos, se valida que efectivamente la clave dinámica y se comprueba que es correcta <p>
                  <b>Entonces:</b> se permite el acceso al sistema<p>
                value:
                  data:
                    usersCredentials:
                      aliasName: jhrodriguez
                      credentials: 9EKH/OMzOx2L6ZG3iLIRFQRN
                    userKey:
                      dynamicKey: 225538

              Clave dinámica no válida:
                description: 
                  <b>Dado:</b> Dado que se desea ingresar al módulo administrativo del sistema CCS, el usuario ingresa la clave dinámica recibida por correo.<p>
                  <b>Cuando:</b> se envían los datos, se valida que efectivamente la clave dinámica y se comprueba que no es correcta <p>
                  <b>Entonces:</b> se permite genera un mensaje de excepción<p>
                value:
                  data:
                    usersCredentials:
                      aliasName: jhrodriguez
                      credentials: 9EKH/OMzOx2L6ZG3iLIRFQRN
                    userKey:
                      dynamicKey: 225548

              Faltan_parámetros_obligatorios:
                description: 
                  <b>Dado:</b> Que no se envian todos los datos obligatorios.<p>
                  <b>Cuando:</b> se consume el api<p>
                  <b>Entonces:</b> Se recibe un mensaje de excepción<p>      
                value:
                  data:
                    usersCredentials:
                      aliasName: jhrodriguez
                      credentials: 9EKH/OMzOx2L6ZG3iLIRFQRN
                    userKey:
                      dynamicKey:
        required: true
        
      responses:
        '200':
          x-success-response: Successfull
          description: Respuesta exitosa
          x-ibm-languages:
            description:
              en: Successful response.          
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dynamicKeyResponse'
              examples:
                Clave dinámica válida:
                  description: 
                    <b>Dado:</b> Dado que se desea ingresar al módulo administrativo del sistema CCS, el usuario ingresa la clave dinámica recibida por correo.<p>
                    <b>Cuando:</b> se envían los datos, se valida que efectivamente la clave dinámica y se comprueba que es correcta <p>
                    <b>Entonces:</b> se permite el acceso al sistema<p>
                  value:
                    data:
                      meta:
                        _requestDateTime: '2024-01-26T14:52:09.779Z'
                        _applicationId: default
                        _messageId: dbff089d-292d-4894-b842-8e88c7003525
                      message: >-
                        Acceso autorizado
        '400':
          description: Bad request
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              examples:
                Faltan parámetros obligatorios:
                      description: 
                        <b>Dado:</b> Que no se envian todos los datos obligatorios.<p>
                        <b>Cuando:</b> se consume el api<p>
                        <b>Entonces:</b> Se recibe un mensaje de excepción<p> 
                      value:
                        data:
                         meta:
                          _requestDateTime: '2024-01-26T14:52:09.779Z'
                          _applicationId: default
                          _messageId: dbff089d-292d-4894-b842-8e88c7003525
                         status: 400
                         title: Bad Resquest
                         errors:
                          - code: BP20252
                            detail: Faltan parámetros obligatorios (credentials)
          x-ibm-languages:
            description:
              en: Error in the request.
        '401':
          description: Credenciales incorrectas.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              examples:
                Clave dinámica no válida:
                  description: 
                    <b>Dado:</b> Dado que se desea ingresar al módulo administrativo del sistema CCS, el usuario ingresa la clave dinámica recibida por correo.<p>
                    <b>Cuando:</b> se envían los datos, se valida que efectivamente la clave dinámica y se comprueba que la clave no es correcta <p>
                    <b>Entonces:</b> se genera un mensaje de excepción<p>
                  value:
                    data:
                     meta:
                      _requestDateTime: '2024-01-26T14:52:09.779Z'
                      _applicationId: default
                      _messageId: dbff089d-292d-4894-b842-8e88c7003525
                     status: 401
                     title: Unauthorized (RFC 7235)
                     errors:
                      - code: BP20256
                        detail: Evento no autorizado
          x-ibm-languages:
            description:
              en: Incorrect credentials.
        '404':
          description: Recurso no encontrado.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              examples:
                Usuario no se encuentra registrado:
                  description: 
                    <b>Dado:</b> Que se envía una alias de un usuario no registrado.<p>
                    <b>Cuando:</b> se consume el api<p>
                    <b>Entonces:</b> Se recibe un mensaje de excepción<p>       
                  value:
                    data:
                     meta:
                      _requestDateTime: '2024-01-26T14:52:09.779Z'
                      _applicationId: default
                      _messageId: dbff089d-292d-4894-b842-8e88c7003525
                     status: 404
                     title: Not Found
                     errors:
                      - code: BP20250
                        detail: No se encontraron registros

          x-ibm-languages:
            description:
              en: Resource not found.
        '409':
          description: >
            El estado del recurso presenta conflictos con los datos de la solicitud.
            ### Códigos de error
            Listado de códigos de error
            | code    | detail                       |
            | ------- | ---------------------------- |
            | BP20270 | Clave vencida                | 

          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              examples:
                Identificador de relación cliente-comercio vencido:
                  description: 
                    <b>Dado:</b> Que se recibe un usuario con credenciales vencidas.<p>
                    <b>Cuando:</b> se consume el api<p>
                    <b>Entonces:</b> Se recibe un mensaje de excepción<p>    
                  value:
                    data:
                     meta:
                      _requestDateTime: '2024-01-26T14:52:09.779Z'
                      _applicationId: default
                      _messageId: dbff089d-292d-4894-b842-8e88c7003525
                     status: 409
                     title: Conflict
                     errors:
                      - code: BP20270
                        detail: Clave vencida
                
          x-ibm-languages:
            description:
              en: Resource state has conflicts with data of the request.
        '500':
          description: Error interno del servidor.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 500
                title: Internal Server Error
                errors:
                  - code: BP20257
                    detail: El evento no pudo ser realizado, intente nuevamente.
          x-ibm-languages:
            description:
              en: Internal server error.
        '502':
          description: Error en la respuesta del proveedor del servicio.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 502
                title: Bad Gateway
                errors:
                  - code: BP20257
                    detail: El evento no pudo ser realizado, intente nuevamente.
          x-ibm-languages:
            description:
              en: Error in the service provider response.
        '503':
          description: Servicio no disponible.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 503
                title: Service Unavailable
                errors:
                  - code: BP20257
                    detail: El evento no pudo ser realizado, intente nuevamente.
          x-ibm-languages:
            description:
              en: Service unavailable.
        '504':
          description: Tiempo de respuesta del proveedor del servicio excedido.
          headers:
            Message-Id: 
              $ref: '#/components/headers/Message-Id'
            RateLimit-Limit:
              $ref: '#/components/headers/RateLimit-Limit'
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            API-Version:
              $ref: '#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRS'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 504
                title: Gateway Timeout
                errors:
                  - code: BP20257
                    detail: El evento no pudo ser realizado, intente nuevamente.
          x-ibm-languages:
            description:
              en: Service provider response time exceeded.
      x-codegen-request-body-name: requestBody
      tags:
        - Validate user credentials
      security:
        - clientSecret: []
          clientId: []          
          
  /health:
    head:
      summary: Metodo que indica el monitoreo del api
      operationId: healthOperation
      responses:
        '200':
          description: Respuesta exitosa.
          x-ibm-languages:
            description:
              en: Successful response.
      security:
        - clientId: []
          clientSecret: []
      tags:
        - Monitoring
        
        
components:

  headers:
    Message-Id:
      description: Identificador del mensaje o de correlación usado para la     trazabilidad de los llamados a las APIs.
      schema:
        type: string
        x-ibm-languages:
          description:
            en: >-
                  Message identifier or correlation identifier used for the
                  traceability of the API calls.
                  
    RateLimit-Limit:
      description: Limite de solicitudes por intervalo de tiempo
      schema:
        type: number
        x-ibm-languages:
          description:
            en: Resquest limit per time interval.
            
    Content-Type:
      description: 'Formato de mensajeria de la API. Ejemplo: application/json.'
      schema:
        type: string
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/json.'
            
    API-Version:
      description: 'Version de la API. Ejemplo: 1.0.0.'
      schema:
        type: string
        x-ibm-languages:
          description:
            en: 'API Version. Example: 1.0.0.'
            
  parameters:            
            
    json-web-token:
      name: json-web-token
      in: header        
      required: true
      description: JWT generado por el consumidor
      schema:
        type: string
      example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
         
    x-client-certificate:
      name: x-client-certificate
      in: header            
      required: true
      description: Certificado configurado en el portal, codificado en Base64 sin saltos de linea
      schema:
        type: string
      example: -----BEGIN CERTIFICATE-----MIIDvjCCAqYCCQCa4y5+b3BvfTANBgkqhkiG9w0BAQsFADCBoDELMAkGA1UEBhMCQ08xEjAQBgNVBAgMCUFOVElPUVVJQTERMA8GA1UEBwwITUVERUxMSU4xGTAXBgNVBAoMEEJBTkNPTE9NQklBIFMuQS4xJjAkBgNVBAsMHVZJQ0VQUkVTSURFTkNJQSBERSBURUNOT0xPR0lBMScwJQYDVQQDDB5wcnVlYmFqd3QuYXBwcy5hbWJpZW50ZXNiYy5jb20wHhcNMjIwMjI0MjE1NTM1WhcNMjMwMjI0MjE1NTM1WjCBoDELMAkGA1UEBhMCQ08xEjAQBgNVBAgMCUFOVElPUVVJQTERMA8GA1UEBwwITUVERUxMSU4xGTAXBgNVBAoMEEJBTkNPTE9NQklBIFMuQS4xJjAkBgNVBAsMHVZJQ0VQUkVTSURFTkNJQSBERSBURUNOT0xPR0lBMScwJQYDVQQDDB5wcnVlYmFqd3QuYXBwcy5hbWJpZW50ZXNiYy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK-----END CERTIFICATE-----     
            
    authorization:
      name: authorization
      in: header
      required: true
      description: >-
        Credenciales de la aplicación, autenticación Basic
      schema:
        type: string
      example: Bearer AAIgZGZmMjE4MTY0MmNiN2VmMWU3YWE4ZGEwOTMyZDg3Nzl1UCIm6i0O-6D-0AEjCFwYMhiIMUoqVtp5dKVVif_EOeoHYhXbujxMXJ-8SIp7lRcoPMcx0VTOJzoQdSzVB5r7uoxdIe9fN3hnhi_NxaJIHug6t3GlyzIhLIwJ5la81agoyFOzne2GOfuo7aZucM3C
            
    accept:
      name: accept
      in: header
      required: true
      description: application/json, el cual representa el formato de mensajería.
      schema:
        type: string
      example: application/vnd.bancolombia.v4+json
      
    message-id:
      name: message-id
      in: header
      required: true
      description: >-
            Identificador de transacción. Se recomienda usar un UUID para el
            valor de este campo.
      schema:
        type: string
        format: uuid
        pattern: >-
                ^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
      example: 693f1c36-d4a2-4c57-aae6-0788dfab7c01

  schemas:    
    ErrorRS:
      description: Objeto que contiene la información del error
      type: object
      properties:
        status:
          allOf:
          - $ref: '#/components/schemas/basicErrorRS'
          - type: object
            properties:
              errors:
                $ref: '#/components/schemas/errors'

    basicErrorRS:
      type: object
      description: Estado de la respuesta
      required:
        - meta      
        - status
        - title
      additionalProperties: false
      properties:
        meta:
          $ref: '#/components/schemas/meta'      
        status:
          $ref: '#/components/schemas/status'
        title:
          $ref: '#/components/schemas/title'

    errors:
      type: array
      description: Lista de errores detectados.
      items:
        properties:
          code:
            $ref: '#/components/schemas/error'

    status:
      type: number
      description: >-
            Codigo de estado HTTP (status code) asociado al mensaje de error de
            la respuesta del llamado a la API.
      example: 404
    title:
      type: string
      description: >-
        Titulo asociado al codigo de estado HTTP (status code) asociado al
        mensaje de error de la respuesta del llamado a la API.
      example: Not Found

    error:
      required:
        - code
        - detail
      type: object
      properties:
        code:
          type: string
          description: An application-specific error code, expressed as a string value.
          example: BP404
        detail:
          type: string
          description: >-
            A human-readable explanation specific to this occurrence of the
            problem.
          example: Requested resource could not be found
  
    validateRequest:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - userCredentials
          properties:
            userCredentials:
              $ref: '#/components/schemas/userCredentials'
              
    dynamicKeyRequest:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - userCredentials
            - userKey
          properties:
            userCredentials:
              $ref: '#/components/schemas/userCredentials'
            userKey:
              $ref: '#/components/schemas/userKey'
              
    userCredentials:
      type: object
      description: Credenciales del usuario
      required:
        - aliasName
        - credentials
      properties:
        aliasName:
          type: string
          description: >-
            Alias con el cual el usuario se encuentra registrado en el sistema
          minLength: 10
          maxLength: 60
          example: 'cmmondragon'
        credentials:
          type: string
          description: >-
            Credenciales codificadas de autenticación del usuario
          minLength: 1
          maxLength: 30
          example: 'AAIgZGZmMjE4MTY0MmNiN2'
          
    userKey:
      type: object
      description: Clave dinámica
      required:
        - dynamicKey
      properties:
        dynamicKey:
          type: string
          description: >-
            Clave dinámica enviada al correo del usuario
          minLength: 8
          maxLength: 8
          example: '556320'

          
    validateResponse:
      type: object
      required:
        - meta
        - data
      properties:
        meta:
          $ref: '#/components/schemas/meta'
        data:
          type: object
          required:
            - expireDate
          properties:
            expireDate:
              type: string
              description: >-
                    Este dato indica el tiempo por el cual es válida la clave dinámica enviada al correo del usuario
              example: '2024-01-26T15:02:09.779Z'
              
    dynamicKeyResponse:
      type: object
      required:
        - meta
      properties:
        meta:
          $ref: '#/components/schemas/meta'
                
    meta:
      required:
        - _applicationId
        - _messageId
        - _requestDateTime
      type: object
      properties:
        _messageId:
          type: string
          format: uuid
          example: 56d6adc5-b25a-4d75-a663-56a62bad4982
        _requestDateTime:
          type: string
          format: date-time
          example: 2016-06-23T16:07:21.205Z
        _applicationId:
          type: string
          example: acxff62e-6f12-42de-9012-3e7304418abd
      description: Datos de trazabilidad e informacion técnica del mensaje.
      
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: Client-Id
      x-key-type: client_id
    clientSecret:
      type: apiKey
      in: header
      name: Client-Secret
      x-key-type: client_secret